const storeSettings = new Fox({
    general:{
        dark_mode:false,
        search:true,
        suggestion:true,
        suggestion_count:100,
        topSites:true,
        topSites_count:3,
        bookmarks:true,
        bookmarks_count:3,
        col_count:5,
        contact_Info:true,
    },
    timeDate:{
        show:true,
        day_formate:'dddd',
        date_formate:''
    },
    background:{
        show:true
    },
},"settings",true);